### ISSUE TITLE
Мой первый issues

### ISSUE THREAD

**Issue by bgdnzhlnsk1** [bgdnzhlnsk1/project-bank#1]
Искать гиперпараметры через GridSearchCV, чтобы ускорить процесс их поиска.

**Comment by Sekai-no-uragawa** [comment]
## Комментарий ревьюера

Привет, Богдан! Меня зовут Михаил Костин, я буду проверять этот проект. Спасибо за проделанную работу! Предлагаю общаться на «ты».

*Давай смотреть, что получилось!*

Супер, все пункты выполнены:
- ✔️Работа над проектом велась последовательно и разбита на отдельные коммиты
- ✔️Описание коммитов соответствуют содержимому
- ✔️Заполнен файл описания проeкта readme
- ✔️Создан issue с возможными улучшениями проекта

От себя могу добавить только, что:
- Readme .md — markdown файл, у него простой синтаксис разметки, оформлять можно очень красиво и функционально, [Шпаргалка](https://www.markdownguide.org/basic-syntax/)
- Хороший [гайд](https://gist.github.com/Voloshin-Sergei/ffbec67c6d9fcb32b0df014ababba0e9) по именованию коммитов
- В readme дальше при оформлении репозитория описывай ход работы, добавляй описание используемых инструментов, полученные метрики.

## Итоговый комментарий ревьюера
Твой проект готов :) Надеюсь, тебе понравилось пользоваться системой версионирования — это действительно очень полезный и удобный инструмент.

**Comment by bgdnzhlnsk1** [comment]
Привет, Михаил. Какого формата\типа должен быть readme, txt, md. doc? Спасибо за доп. информацию!

**Comment by Sekai-no-uragawa** [comment]
.md, как сейчас у тебя. Просто стоит немного разобраться в синтаксисе, но он очень простой. Можно экспериментировать прямо тут, нажимая на кнопку Preview или пользоваться онлайн Markdown редактором, например https://dillinger.io/

**Comment by bgdnzhlnsk1** [comment]
Благодарю, Михаил, за ответ на мой вопрос!
